package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
)

type SerpsbotSuggestions struct {
	Meta struct {
		Gl       string   `json:"gl"`
		Hl       string   `json:"hl"`
		Keywords []string `json:"keywords"`
	} `json:"meta"`
	Data []struct {
		Keyword     string   `json:"keyword"`
		Suggestions []string `json:"suggestions"`
	} `json:"data"`
}

func WriteStringToFile(filename string, line string) error {
	f, err := os.OpenFile(filename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(line)
	if err != nil {
		return err
	}
	return nil
}

func SerpsGetSuggestions(keywords []string, apikey string, gl string, hl string) (SerpsbotSuggestions, error) {

	type AutoGenerated struct {
		Gl       string   `json:"gl"`
		Hl       string   `json:"hl"`
		Keywords []string `json:"keywords"`
	}

	type AutoGenerated2 struct {
		Detail []struct {
			Loc  []interface{} `json:"loc"`
			Msg  string        `json:"msg"`
			Type string        `json:"type"`
		} `json:"detail"`
	}

	api := AutoGenerated{
		Gl:       "us",
		Hl:       "en_US",
		Keywords: keywords,
	}

	var x SerpsbotSuggestions

	//fmt.Println(api)

	// create requesta
	b, _ := json.Marshal(api)

	req, err := http.NewRequest("POST", "https://api.serpsbot.com/v2/google/search-suggestions", bytes.NewBuffer(b))
	if err != nil {
		fmt.Println(err)
		return x, err
	}
	// fmt.Println(w.FormDataContentType())
	req.Header.Set("X-API-KEY", apikey)
	// send request
	client := &http.Client{}
	res, err := client.Do(req)
	if err != nil {
		fmt.Println(err)
		return x, err
	}
	defer res.Body.Close()
	// fmt.Println(res)

	if res.StatusCode != 200 {
		// probably 422 error, so decode the error
		var a AutoGenerated2
		err = json.NewDecoder(res.Body).Decode(&a)
		if err != nil {
			log.Fatalln(err)
			return x, err
		}
		fmt.Println(a)
	} else {

		err = json.NewDecoder(res.Body).Decode(&x)
		if err != nil {
			log.Fatalln(err)
			return x, err
		}
		//fmt.Println(x)
		//for _, v := range x.Data {
		//fmt.Println(v.Keyword)
		//for _, v2 := range v.Suggestions {
		//fmt.Println("-", v2)
		//}
		//}

		return x, nil
	}
	return x, errors.New("Error")
}

func main() {
	fmt.Println("SerpsBot v1.0 by ToyBlackHat")

	keywords_cli := flag.String("keywords", "", "Keyword to get suggestions from Google")
	apikey_cli := flag.String("apikey", "", "Serpsbot API Key")
	outputfile_cli := flag.String("outputfile", "", "Output file to save results to")
	inputfile_cli := flag.String("inputfile", "", "Input file with keywords to get suggestions from Google")
	gl_cli := flag.String("gl", "US", "The ISO code of the country for which you want to get the suggestions for")
	hl_cli := flag.String("hl", "en_US", "The language to get the suggestions for.")
	merge_cli := flag.Bool("merge", false, "Add keywords from input to the output (result) file")

	flag.Parse()

	if *keywords_cli == "" && *inputfile_cli == "" {
		fmt.Println("Please specify a keyword(s) for --keywords= or a file with keywords for --inputfile=")
		os.Exit(1)
	}
	if *keywords_cli != "" && *inputfile_cli != "" {
		fmt.Println("You can only select one mode --keywords= or --inputfile=")
		os.Exit(1)
	}
	if *apikey_cli == "" {
		fmt.Println("Please enter your Serpsbot apikey into --apikey=")
		os.Exit(1)
	}

	var keywords []string

	if *keywords_cli != "" {
		// Process keywords from command line --keywords=
		keywords = strings.Split(*keywords_cli, ",")
	}

	if *inputfile_cli != "" {
		// Process keywords from file --inputfile=
		file, err := os.Open(*inputfile_cli)
		if err != nil {
			fmt.Println("error opening file:", err)
			return
		}
		defer file.Close()

		scanner := bufio.NewScanner(file)
		for scanner.Scan() {
			keywords = append(keywords, strings.TrimSpace(scanner.Text()))
		}
		if err := scanner.Err(); err != nil {
			fmt.Println("error reading file:", err)
			os.Exit(1)
		}
	}

	for i := 0; i < len(keywords); i += 50 {
		end := i + 50
		if end > len(keywords) {
			end = len(keywords)
		}
		keywords50 := keywords[i:end]

		fmt.Println("Processing", len(keywords50), "keywords, gl=", *gl_cli, "hl=", *hl_cli, "")
		result, err := SerpsGetSuggestions(keywords50, *apikey_cli, *gl_cli, *hl_cli)
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}

		for _, v := range result.Data {
			fmt.Println(v.Keyword)
			if *merge_cli {
				//open file and append v.Keyword then close file
				if *outputfile_cli != "" {
					err = WriteStringToFile(*outputfile_cli, v.Keyword+"\n")
					if err != nil {
						fmt.Println(err)
						os.Exit(1)
					}
				}
			}
			for _, v2 := range v.Suggestions {
				fmt.Println("-", v2)
				//open file and append v2 then close file
				if *outputfile_cli != "" {
					err = WriteStringToFile(*outputfile_cli, v2+"\n")
					if err != nil {
						fmt.Println(err)
						os.Exit(1)
					}
				}
			}
		}
	}

}
